// Converts a particle config into EXACT Roblox Luau.
// The output is valid to paste into the Studio Command Bar, a Script, or to
// feed the companion plugin. Property names + value types match the Roblox
// ParticleEmitter API exactly.

function num(n) {
  // Trim float noise but keep precision Roblox cares about.
  return Number.isInteger(n) ? String(n) : String(Math.round(n * 1000) / 1000);
}

function colorSequence(kps) {
  const parts = kps.map(
    (k) =>
      `\t\tColorSequenceKeypoint.new(${num(k.t)}, Color3.fromRGB(${Math.round(
        k.c[0]
      )}, ${Math.round(k.c[1])}, ${Math.round(k.c[2])}))`
  );
  return `ColorSequence.new({\n${parts.join(",\n")}\n\t})`;
}

function numberSequence(kps) {
  const parts = kps.map((k) => {
    const env = k.e ? `, ${num(k.e)}` : "";
    return `\t\tNumberSequenceKeypoint.new(${num(k.t)}, ${num(k.v)}${env})`;
  });
  return `NumberSequence.new({\n${parts.join(",\n")}\n\t})`;
}

/**
 * Build the body of property assignments (shared by snippet + plugin + module).
 * `v` is the local variable name the emitter is bound to.
 */
export function emitterAssignments(cfg, v = "emitter") {
  const L = [];
  L.push(`${v}.Texture = "${cfg.texture}"`);
  L.push(`${v}.Rate = ${num(cfg.rate)}`);
  L.push(`${v}.Lifetime = NumberRange.new(${num(cfg.lifetime[0])}, ${num(cfg.lifetime[1])})`);
  L.push(`${v}.Speed = NumberRange.new(${num(cfg.speed[0])}, ${num(cfg.speed[1])})`);
  L.push(`${v}.SpreadAngle = Vector2.new(${num(cfg.spreadAngle[0])}, ${num(cfg.spreadAngle[1])})`);
  L.push(`${v}.Rotation = NumberRange.new(${num(cfg.rotation[0])}, ${num(cfg.rotation[1])})`);
  L.push(`${v}.RotSpeed = NumberRange.new(${num(cfg.rotSpeed[0])}, ${num(cfg.rotSpeed[1])})`);
  L.push(`${v}.Acceleration = Vector3.new(${num(cfg.acceleration[0])}, ${num(cfg.acceleration[1])}, ${num(cfg.acceleration[2])})`);
  L.push(`${v}.Drag = ${num(cfg.drag)}`);
  L.push(`${v}.LightEmission = ${num(cfg.lightEmission)}`);
  L.push(`${v}.LightInfluence = ${num(cfg.lightInfluence)}`);
  L.push(`${v}.Brightness = ${num(cfg.brightness)}`);
  L.push(`${v}.ZOffset = ${num(cfg.zOffset)}`);
  L.push(`${v}.TimeScale = ${num(cfg.timeScale)}`);
  L.push(`${v}.EmissionDirection = Enum.NormalId.${cfg.emissionDirection}`);
  L.push(`${v}.Orientation = Enum.ParticleOrientation.${cfg.orientation}`);
  L.push(`${v}.Enabled = ${cfg.enabled ? "true" : "false"}`);
  L.push(`${v}.Color = ${colorSequence(cfg.color)}`);
  L.push(`${v}.Size = ${numberSequence(cfg.size)}`);
  L.push(`${v}.Transparency = ${numberSequence(cfg.transparency)}`);
  return L.map((line) => "\t" + line).join("\n");
}

/**
 * Full paste-and-run snippet. Applies the emitter to the current Studio
 * Selection (or workspace if nothing selected). Drop into the Command Bar.
 */
export function toLuauSnippet(cfg) {
  const fnName = "applyVFX";
  return `-- ${cfg.name} VFX -- generated by Roblox VFX Forge
-- Paste into the Studio Command Bar, then it attaches to your selected Part(s).
local Selection = game:GetService("Selection")

local function ${fnName}(parent)
\tlocal emitter = Instance.new("ParticleEmitter")
${emitterAssignments(cfg, "emitter")}
\temitter.Parent = parent
\treturn emitter
end

local targets = Selection:Get()
if #targets == 0 then
\twarn("[VFX Forge] Nothing selected -- select a Part/Attachment first.")
else
\tfor _, target in ipairs(targets) do
\t\t${fnName}(target)
\tend
\tprint("[VFX Forge] Applied '" .. "${cfg.name}" .. "' to " .. #targets .. " object(s).")
end`;
}

/**
 * ModuleScript form: returns a builder function. Good for committing to a
 * game's source so emitters can be spawned at runtime.
 */
export function toLuauModule(cfg) {
  return `--!strict
-- ${cfg.name} VFX module -- generated by Roblox VFX Forge
-- Usage: require(this)(somePart)
return function(parent: Instance): ParticleEmitter
\tlocal emitter = Instance.new("ParticleEmitter")
${emitterAssignments(cfg, "emitter")}
\temitter.Parent = parent
\treturn emitter
end`;
}
