// Curated bilingual question banks for conceptual subjects, tagged by school
// year (lv). Math and upper physics are procedurally generated in games.ts;
// these banks carry the subjects where questions must be authored.

import type { QuizQ } from "./games";

export interface TaggedQ extends QuizQ {
  lv: number;
}

export const PHYSICS_EARLY_BANK: Record<number, QuizQ[]> = {
  1: [
    {
      q: { en: "Which of these will float in water?", ar: "أي مما يلي يطفو على الماء؟" },
      choices: [
        { en: "A wooden spoon", ar: "ملعقة خشبية" },
        { en: "A metal key", ar: "مفتاح معدني" },
        { en: "A stone", ar: "حجر" },
        { en: "A coin", ar: "قطعة نقود" },
      ],
      correct: 0,
      explain: { en: "Wood is lighter than the same amount of water, so it floats.", ar: "الخشب أخف من كمية الماء المساوية له حجماً، لذلك يطفو." },
    },
    {
      q: { en: "To make a toy car move, you must…", ar: "لتحريك سيارة لعبة يجب أن…" },
      choices: [
        { en: "Push or pull it", ar: "تدفعها أو تسحبها" },
        { en: "Look at it", ar: "تنظر إليها" },
        { en: "Name it", ar: "تسمّيها" },
        { en: "Paint it", ar: "تلوّنها" },
      ],
      correct: 0,
      explain: { en: "Things move when a force — a push or a pull — acts on them.", ar: "تتحرك الأشياء حين تؤثر فيها قوة — دفعٌ أو سحب." },
    },
    {
      q: { en: "Which material lets light pass through?", ar: "أي مادة تسمح للضوء بالمرور عبرها؟" },
      choices: [
        { en: "Clear glass", ar: "الزجاج الشفاف" },
        { en: "A brick", ar: "قطعة طوب" },
        { en: "A wooden door", ar: "باب خشبي" },
        { en: "A metal tray", ar: "صينية معدنية" },
      ],
      correct: 0,
      explain: { en: "Glass is transparent — light passes straight through it.", ar: "الزجاج شفاف — يمر الضوء عبره مباشرة." },
    },
  ],
  2: [
    {
      q: { en: "Why is it hard to slide on a rough carpet?", ar: "لماذا يصعب الانزلاق على سجادة خشنة؟" },
      choices: [
        { en: "Friction is high", ar: "الاحتكاك كبير" },
        { en: "The carpet is cold", ar: "السجادة باردة" },
        { en: "Gravity is stronger", ar: "الجاذبية أقوى" },
        { en: "The air pushes back", ar: "الهواء يقاوم" },
      ],
      correct: 0,
      explain: { en: "Rough surfaces grip: high friction resists sliding.", ar: "الأسطح الخشنة تُمسك: الاحتكاك العالي يقاوم الانزلاق." },
    },
    {
      q: { en: "Which will a magnet attract?", ar: "أي شيء يجذبه المغناطيس؟" },
      choices: [
        { en: "An iron nail", ar: "مسمار حديدي" },
        { en: "A plastic ruler", ar: "مسطرة بلاستيكية" },
        { en: "A wooden pencil", ar: "قلم خشبي" },
        { en: "A paper sheet", ar: "ورقة" },
      ],
      correct: 0,
      explain: { en: "Magnets attract iron and steel, not plastic, wood or paper.", ar: "يجذب المغناطيس الحديد والفولاذ، لا البلاستيك أو الخشب أو الورق." },
    },
    {
      q: { en: "A ramp (slope) helps you move a heavy box by…", ar: "المنحدر يساعدك على تحريك صندوق ثقيل عبر…" },
      choices: [
        { en: "Spreading the effort over a longer path", ar: "توزيع الجهد على مسافة أطول" },
        { en: "Making the box lighter", ar: "جعل الصندوق أخف وزناً" },
        { en: "Removing gravity", ar: "إلغاء الجاذبية" },
        { en: "Heating the box", ar: "تسخين الصندوق" },
      ],
      correct: 0,
      explain: { en: "Simple machines trade a longer distance for a smaller force.", ar: "الآلات البسيطة تستبدل قوة أصغر بمسافة أطول." },
    },
  ],
  3: [
    {
      q: { en: "A shadow forms because light…", ar: "يتكوّن الظل لأن الضوء…" },
      choices: [
        { en: "Travels in straight lines", ar: "ينتقل في خطوط مستقيمة" },
        { en: "Is very hot", ar: "ساخن جداً" },
        { en: "Moves slowly", ar: "يتحرك ببطء" },
        { en: "Is yellow", ar: "أصفر اللون" },
      ],
      correct: 0,
      explain: { en: "Light can't bend around an object, so a dark shape appears behind it.", ar: "لا يستطيع الضوء الالتفاف حول الجسم، فيظهر شكل مظلم خلفه." },
    },
    {
      q: { en: "Sound is made by…", ar: "ينشأ الصوت من…" },
      choices: [
        { en: "Vibrations", ar: "الاهتزازات" },
        { en: "Light", ar: "الضوء" },
        { en: "Shadows", ar: "الظلال" },
        { en: "Heat", ar: "الحرارة" },
      ],
      correct: 0,
      explain: { en: "Anything that vibrates pushes the air in waves we hear as sound.", ar: "كل ما يهتز يدفع الهواء في موجات نسمعها صوتاً." },
    },
    {
      q: { en: "At noon in the desert, your shadow is…", ar: "عند الظهيرة في الصحراء يكون ظلك…" },
      choices: [
        { en: "Shortest", ar: "في أقصر حالاته" },
        { en: "Longest", ar: "في أطول حالاته" },
        { en: "Gone completely", ar: "مختفياً تماماً" },
        { en: "Behind you always", ar: "خلفك دائماً" },
      ],
      correct: 0,
      explain: { en: "The higher the sun, the shorter the shadow — highest at noon.", ar: "كلما ارتفعت الشمس قصر الظل — وهي في أعلاها ظهراً." },
    },
  ],
  4: [
    {
      q: { en: "When ice melts it becomes…", ar: "عندما يذوب الجليد يتحول إلى…" },
      choices: [
        { en: "Liquid water", ar: "ماء سائل" },
        { en: "Steam only", ar: "بخار فقط" },
        { en: "A new solid", ar: "مادة صلبة جديدة" },
        { en: "Air", ar: "هواء" },
      ],
      correct: 0,
      explain: { en: "Melting is the change from solid to liquid — same water, new state.", ar: "الانصهار تحوّل من الحالة الصلبة إلى السائلة — الماء نفسه بحالة جديدة." },
    },
    {
      q: { en: "Wet clothes dry on a line because water…", ar: "تجف الملابس المبللة على الحبل لأن الماء…" },
      choices: [
        { en: "Evaporates", ar: "يتبخر" },
        { en: "Freezes", ar: "يتجمد" },
        { en: "Melts", ar: "ينصهر" },
        { en: "Disappears forever", ar: "يختفي إلى الأبد" },
      ],
      correct: 0,
      explain: { en: "Heat turns liquid water into invisible vapour that rises into the air.", ar: "تحوّل الحرارة الماء السائل إلى بخار غير مرئي يرتفع في الهواء." },
    },
    {
      q: { en: "Which state of matter keeps its shape on its own?", ar: "أي حالة من حالات المادة تحتفظ بشكلها من تلقاء نفسها؟" },
      choices: [
        { en: "Solid", ar: "الصلبة" },
        { en: "Liquid", ar: "السائلة" },
        { en: "Gas", ar: "الغازية" },
        { en: "None of them", ar: "لا شيء منها" },
      ],
      correct: 0,
      explain: { en: "Solids hold their shape; liquids take the container's shape; gases fill the space.", ar: "الصلبة تحتفظ بشكلها؛ والسائلة تأخذ شكل الوعاء؛ والغازية تملأ الفراغ." },
    },
  ],
  5: [
    {
      q: { en: "A battery in a torch stores…", ar: "تخزّن البطارية في المصباح…" },
      choices: [
        { en: "Chemical energy", ar: "طاقة كيميائية" },
        { en: "Sound energy", ar: "طاقة صوتية" },
        { en: "Wind energy", ar: "طاقة رياح" },
        { en: "Shadow energy", ar: "طاقة الظل" },
      ],
      correct: 0,
      explain: { en: "The battery's chemical energy becomes electrical, then light.", ar: "تتحول الطاقة الكيميائية في البطارية إلى كهرباء ثم إلى ضوء." },
    },
    {
      q: { en: "For a bulb to light, the circuit must be…", ar: "لكي يضيء المصباح يجب أن تكون الدارة…" },
      choices: [
        { en: "Closed (complete)", ar: "مغلقة (مكتملة)" },
        { en: "Open (broken)", ar: "مفتوحة (مقطوعة)" },
        { en: "Wet", ar: "مبللة" },
        { en: "Very long", ar: "طويلة جداً" },
      ],
      correct: 0,
      explain: { en: "Current only flows around an unbroken loop.", ar: "لا يسري التيار إلا في حلقة غير مقطوعة." },
    },
    {
      q: { en: "Solar panels in the Gulf turn sunlight into…", ar: "تحوّل الألواح الشمسية في الخليج ضوء الشمس إلى…" },
      choices: [
        { en: "Electrical energy", ar: "طاقة كهربائية" },
        { en: "Sound energy", ar: "طاقة صوتية" },
        { en: "More sunlight", ar: "مزيد من ضوء الشمس" },
        { en: "Water", ar: "ماء" },
      ],
      correct: 0,
      explain: { en: "Energy changes form: light in, electricity out.", ar: "تتحول الطاقة من شكل إلى آخر: ضوء يدخل وكهرباء تخرج." },
    },
  ],
};

export const BANKS: Record<string, TaggedQ[]> = {
  geography: [
    {
      lv: 1,
      q: { en: "A map is…", ar: "الخريطة هي…" },
      choices: [
        { en: "A drawing of a place seen from above", ar: "رسم لمكان كما يُرى من الأعلى" },
        { en: "A photo of the sky", ar: "صورة للسماء" },
        { en: "A list of names", ar: "قائمة أسماء" },
        { en: "A kind of book only", ar: "نوع من الكتب فقط" },
      ],
      correct: 0,
      explain: { en: "Maps show places from a bird's-eye view so we can find our way.", ar: "تعرض الخرائط الأماكن من منظور الطائر لنعرف طريقنا." },
    },
    {
      lv: 2,
      q: { en: "A wadi is…", ar: "الوادي هو…" },
      choices: [
        { en: "A valley that fills with water after rain", ar: "منخفض يمتلئ بالماء بعد المطر" },
        { en: "A type of mountain", ar: "نوع من الجبال" },
        { en: "A sea animal", ar: "حيوان بحري" },
        { en: "A sand storm", ar: "عاصفة رملية" },
      ],
      correct: 0,
      explain: { en: "Wadis are dry riverbeds most of the year — and dangerous in flash floods.", ar: "الأودية مجارٍ جافة معظم السنة — وخطرة عند السيول." },
    },
    {
      lv: 3,
      q: { en: "On a compass, the sun rises in the…", ar: "على البوصلة، تشرق الشمس من جهة…" },
      choices: [{ en: "East", ar: "الشرق" }, { en: "West", ar: "الغرب" }, { en: "North", ar: "الشمال" }, { en: "South", ar: "الجنوب" }],
      correct: 0,
      explain: { en: "Earth spins toward the east, so the sun appears there first.", ar: "تدور الأرض نحو الشرق، فتظهر الشمس هناك أولاً." },
    },
    {
      lv: 4,
      q: { en: "In the water cycle, clouds form when water vapour…", ar: "في دورة الماء، تتكوّن الغيوم حين يقوم بخار الماء بـ…" },
      choices: [
        { en: "Condenses into tiny droplets", ar: "التكاثف إلى قطيرات دقيقة" },
        { en: "Freezes into sand", ar: "التجمد إلى رمل" },
        { en: "Evaporates again", ar: "التبخر مجدداً" },
        { en: "Sinks into the ground", ar: "التسرب إلى الأرض" },
      ],
      correct: 0,
      explain: { en: "Rising vapour cools and condenses — millions of droplets make a cloud.", ar: "يبرد البخار الصاعد ويتكاثف — ملايين القطيرات تصنع غيمة." },
    },
    {
      lv: 5,
      q: { en: "Which strait connects the Gulf to the open ocean?", ar: "أي مضيق يصل الخليج بالمحيط المفتوح؟" },
      choices: [{ en: "Hormuz", ar: "هرمز" }, { en: "Gibraltar", ar: "جبل طارق" }, { en: "Bosphorus", ar: "البوسفور" }, { en: "Malacca", ar: "ملقا" }],
      correct: 0,
      explain: { en: "The Strait of Hormuz links the Arabian Gulf to the Gulf of Oman and the Indian Ocean.", ar: "يصل مضيق هرمز الخليج العربي بخليج عُمان والمحيط الهندي." },
    },
    {
      lv: 6,
      q: { en: "People often migrate to cities mainly for…", ar: "يهاجر الناس إلى المدن غالباً بحثاً عن…" },
      choices: [
        { en: "Jobs and services", ar: "العمل والخدمات" },
        { en: "Colder weather", ar: "طقس أبرد" },
        { en: "Bigger deserts", ar: "صحارى أوسع" },
        { en: "Fewer people", ar: "عدد أقل من الناس" },
      ],
      correct: 0,
      explain: { en: "Work, schools and hospitals pull people toward cities — that's urbanisation.", ar: "العمل والمدارس والمستشفيات تجذب الناس إلى المدن — هذا هو التحضّر." },
    },
    {
      lv: 7,
      q: { en: "Gulf states invest in tourism and tech mainly to…", ar: "تستثمر دول الخليج في السياحة والتقنية أساساً من أجل…" },
      choices: [
        { en: "Diversify beyond oil", ar: "تنويع الاقتصاد بعيداً عن النفط" },
        { en: "Use up extra sand", ar: "استهلاك الرمال الزائدة" },
        { en: "Cool the climate", ar: "تبريد المناخ" },
        { en: "Export more oil", ar: "تصدير مزيد من النفط" },
      ],
      correct: 0,
      explain: { en: "Depending on one resource is risky; diversification builds a durable economy.", ar: "الاعتماد على مورد واحد مخاطرة؛ التنويع يبني اقتصاداً صامداً." },
    },
    {
      lv: 8,
      q: { en: "Desertification means…", ar: "التصحّر يعني…" },
      choices: [
        { en: "Fertile land becoming desert", ar: "تحوّل الأرض الخصبة إلى صحراء" },
        { en: "Deserts becoming forests", ar: "تحوّل الصحارى إلى غابات" },
        { en: "Building cities in deserts", ar: "بناء المدن في الصحارى" },
        { en: "Sand storms in winter", ar: "عواصف رملية شتوية" },
      ],
      correct: 0,
      explain: { en: "Overgrazing, drought and misuse turn productive land into desert.", ar: "الرعي الجائر والجفاف وسوء الاستخدام تحوّل الأرض المنتجة إلى صحراء." },
    },
    {
      lv: 9,
      q: { en: "A geographic 'chokepoint' is…", ar: "«الممر الحرج» جغرافياً هو…" },
      choices: [
        { en: "A narrow passage vital to trade", ar: "ممر ضيق حيوي للتجارة" },
        { en: "A mountain peak", ar: "قمة جبلية" },
        { en: "A closed border", ar: "حدود مغلقة" },
        { en: "A big city", ar: "مدينة كبيرة" },
      ],
      correct: 0,
      explain: { en: "Straits and canals like Hormuz and Suez concentrate world trade into narrow waters.", ar: "المضائق والقنوات كهرمز والسويس تحصر تجارة العالم في مياه ضيقة." },
    },
    {
      lv: 10,
      q: { en: "GIS lets geographers…", ar: "تتيح نظم المعلومات الجغرافية للجغرافيين…" },
      choices: [
        { en: "Layer data on digital maps to answer questions", ar: "تركيب طبقات بيانات على خرائط رقمية للإجابة عن الأسئلة" },
        { en: "Control the weather", ar: "التحكم في الطقس" },
        { en: "Move mountains", ar: "نقل الجبال" },
        { en: "Replace all fieldwork", ar: "الاستغناء عن العمل الميداني كلياً" },
      ],
      correct: 0,
      explain: { en: "Population + water + roads layered together reveal patterns no single map shows.", ar: "تركيب طبقات السكان والمياه والطرق معاً يكشف أنماطاً لا تظهرها خريطة واحدة." },
    },
  ],
  ai: [
    {
      lv: 1,
      q: { en: "Which of these uses AI?", ar: "أي مما يلي يستخدم الذكاء الاصطناعي؟" },
      choices: [
        { en: "A voice assistant that answers you", ar: "مساعد صوتي يجيبك" },
        { en: "A wooden chair", ar: "كرسي خشبي" },
        { en: "A glass of water", ar: "كوب ماء" },
        { en: "A paper notebook", ar: "دفتر ورقي" },
      ],
      correct: 0,
      explain: { en: "Voice assistants understand speech and answer — that takes AI.", ar: "المساعدات الصوتية تفهم الكلام وتجيب — وهذا يتطلب ذكاءً اصطناعياً." },
    },
    {
      lv: 2,
      q: { en: "An algorithm is most like a…", ar: "الخوارزمية أشبه ما تكون بـ…" },
      choices: [{ en: "Recipe", ar: "وصفة طبخ" }, { en: "Painting", ar: "لوحة" }, { en: "Song", ar: "أغنية" }, { en: "Ball", ar: "كرة" }],
      correct: 0,
      explain: { en: "Both are exact steps followed in order to get a result.", ar: "كلاهما خطوات دقيقة تُتَّبع بالترتيب للوصول إلى نتيجة." },
    },
    {
      lv: 3,
      q: { en: "A chart that makes a small difference look huge is…", ar: "الرسم البياني الذي يجعل فرقاً صغيراً يبدو ضخماً هو…" },
      choices: [
        { en: "Misleading", ar: "مضلِّل" },
        { en: "More accurate", ar: "أكثر دقة" },
        { en: "Always wrong numbers", ar: "أرقام خاطئة دائماً" },
        { en: "Impossible", ar: "مستحيل" },
      ],
      correct: 0,
      explain: { en: "Cutting the axis or stretching the scale can mislead without lying about the numbers.", ar: "قصّ المحور أو تمديد المقياس قد يضلّل دون كذب في الأرقام نفسها." },
    },
    {
      lv: 4,
      q: { en: "We test a model on data it never saw, to check it…", ar: "نختبر النموذج على بيانات لم يرها من قبل للتحقق من أنه…" },
      choices: [
        { en: "Learned the pattern, not memorised examples", ar: "تعلّم النمط ولم يحفظ الأمثلة" },
        { en: "Is fast enough", ar: "سريع كفاية" },
        { en: "Uses little power", ar: "يستهلك طاقة قليلة" },
        { en: "Has a nice name", ar: "يحمل اسماً جميلاً" },
      ],
      correct: 0,
      explain: { en: "Memorising the training data is easy; generalising to new data is learning.", ar: "حفظ بيانات التدريب سهل؛ أما التعميم على بيانات جديدة فهو التعلّم الحقيقي." },
    },
    {
      lv: 5,
      q: { en: "In supervised learning, the model learns from…", ar: "في التعلّم الموجّه، يتعلم النموذج من…" },
      choices: [
        { en: "Labelled examples", ar: "أمثلة موسومة" },
        { en: "Pure guessing", ar: "التخمين المحض" },
        { en: "Its dreams", ar: "أحلامه" },
        { en: "One example only", ar: "مثال واحد فقط" },
      ],
      correct: 0,
      explain: { en: "Each training example comes with the right answer attached.", ar: "كل مثال تدريبي يأتي مرفقاً بالإجابة الصحيحة." },
    },
    {
      lv: 6,
      q: { en: "A language model writes by repeatedly…", ar: "يكتب نموذج اللغة عبر تكرار…" },
      choices: [
        { en: "Predicting the next token", ar: "التنبؤ بالرمز التالي" },
        { en: "Copying one book", ar: "نسخ كتاب واحد" },
        { en: "Asking a human each word", ar: "سؤال إنسان عن كل كلمة" },
        { en: "Rolling dice blindly", ar: "رمي النرد عشوائياً" },
      ],
      correct: 0,
      explain: { en: "Token by token, it picks what most plausibly comes next given everything so far.", ar: "رمزاً بعد رمز، يختار الأرجح تالياً بناءً على كل ما سبق." },
    },
    {
      lv: 7,
      q: { en: "The best first move when an AI answer looks wrong is to…", ar: "أفضل خطوة أولى حين تبدو إجابة الذكاء الاصطناعي خاطئة هي…" },
      choices: [
        { en: "Verify it against a trusted source", ar: "التحقق منها من مصدر موثوق" },
        { en: "Share it anyway", ar: "نشرها على أي حال" },
        { en: "Assume it's right", ar: "افتراض صحتها" },
        { en: "Delete the app", ar: "حذف التطبيق" },
      ],
      correct: 0,
      explain: { en: "Models can hallucinate; verification is part of using AI well.", ar: "قد تهلوس النماذج؛ التحقق جزء من حسن استخدام الذكاء الاصطناعي." },
    },
    {
      lv: 8,
      q: { en: "The right first step of an AI project is defining…", ar: "الخطوة الأولى الصحيحة في مشروع ذكاء اصطناعي هي تحديد…" },
      choices: [
        { en: "The problem and who it serves", ar: "المشكلة ومن سيخدمها الحل" },
        { en: "The logo", ar: "الشعار" },
        { en: "The office", ar: "المكتب" },
        { en: "The launch party", ar: "حفل الإطلاق" },
      ],
      correct: 0,
      explain: { en: "Technology chosen before the problem is a solution looking for a use.", ar: "التقنية المختارة قبل المشكلة حلٌّ يبحث عن استخدام." },
    },
    {
      lv: 9,
      q: { en: "A face-recognition model trained mostly on one group will…", ar: "نموذج تمييز وجوه دُرّب غالباً على فئة واحدة سوف…" },
      choices: [
        { en: "Perform worse on other groups", ar: "يكون أداؤه أسوأ مع الفئات الأخرى" },
        { en: "Work equally for everyone", ar: "يعمل بالتساوي مع الجميع" },
        { en: "Refuse to run", ar: "يرفض العمل" },
        { en: "Fix itself automatically", ar: "يصلح نفسه تلقائياً" },
      ],
      correct: 0,
      explain: { en: "Bias in the data becomes bias in the model — that's why diverse data matters.", ar: "التحيّز في البيانات يصبح تحيّزاً في النموذج — لهذا تُهم البيانات المتنوعة." },
    },
    {
      lv: 10,
      q: { en: "An AI 'agent' differs from a chatbot because it can…", ar: "يختلف «الوكيل» الذكي عن روبوت المحادثة في قدرته على…" },
      choices: [
        { en: "Take multi-step actions with tools", ar: "تنفيذ خطوات متعددة باستخدام أدوات" },
        { en: "Only chat longer", ar: "الدردشة لوقت أطول فقط" },
        { en: "Avoid all mistakes", ar: "تجنّب كل الأخطاء" },
        { en: "Feel emotions", ar: "الشعور بالعواطف" },
      ],
      correct: 0,
      explain: { en: "Agents plan, call tools, check results and keep going — not just reply.", ar: "الوكلاء يخططون ويستدعون الأدوات ويتحققون من النتائج ويواصلون — لا يكتفون بالرد." },
    },
  ],
  gaming: [
    {
      lv: 1,
      q: { en: "A game without rules is…", ar: "اللعبة بلا قواعد هي…" },
      choices: [
        { en: "Just play — nobody can win or lose", ar: "مجرد لهو — لا فوز فيها ولا خسارة" },
        { en: "More fair", ar: "أكثر عدلاً" },
        { en: "Impossible to enjoy", ar: "مستحيلة المتعة" },
        { en: "Always boring", ar: "مملة دائماً" },
      ],
      correct: 0,
      explain: { en: "Rules create goals and fairness — that's what turns play into a game.", ar: "القواعد تصنع الأهداف والعدل — وهي ما يحوّل اللهو إلى لعبة." },
    },
    {
      lv: 2,
      q: { en: "A good rulebook is one that…", ar: "كتيّب القواعد الجيد هو الذي…" },
      choices: [
        { en: "A stranger can follow without you", ar: "يستطيع شخص غريب اتباعه دونك" },
        { en: "Only you understand", ar: "لا يفهمه غيرك" },
        { en: "Is as long as possible", ar: "يكون أطول ما يمكن" },
        { en: "Changes every round", ar: "يتغير كل جولة" },
      ],
      correct: 0,
      explain: { en: "If players need you to explain, the rules aren't finished yet.", ar: "إذا احتاج اللاعبون شرحك، فالقواعد لم تكتمل بعد." },
    },
    {
      lv: 3,
      q: { en: "A game stays fun when challenge is…", ar: "تبقى اللعبة ممتعة حين يكون التحدي…" },
      choices: [
        { en: "Slightly above your skill", ar: "أعلى قليلاً من مهارتك" },
        { en: "Impossible", ar: "مستحيلاً" },
        { en: "Absent", ar: "غائباً" },
        { en: "Random", ar: "عشوائياً تماماً" },
      ],
      correct: 0,
      explain: { en: "That balance point is called 'flow' — hard enough to grip, fair enough to win.", ar: "تلك النقطة تسمى «الانسياب» — صعبة بما يكفي لتشدّك وعادلة بما يكفي لتفوز." },
    },
    {
      lv: 4,
      q: { en: "Good levels teach new mechanics by…", ar: "المراحل الجيدة تعلّم الميكانيكيات الجديدة عبر…" },
      choices: [
        { en: "A safe place to try before the danger", ar: "مكان آمن للتجربة قبل الخطر" },
        { en: "A long text tutorial", ar: "شرح نصي طويل" },
        { en: "Punishing mistakes instantly", ar: "معاقبة الأخطاء فوراً" },
        { en: "Hiding the mechanic", ar: "إخفاء الميكانيكية" },
      ],
      correct: 0,
      explain: { en: "Show, let them try safely, then test — teaching without words.", ar: "اعرض، ودعهم يجربون بأمان، ثم اختبر — تعليم دون كلمات." },
    },
    {
      lv: 5,
      q: { en: "Branching stories give players…", ar: "القصص المتفرعة تمنح اللاعبين…" },
      choices: [
        { en: "Choices with consequences", ar: "خيارات ذات عواقب" },
        { en: "Shorter games", ar: "ألعاباً أقصر" },
        { en: "Fewer characters", ar: "شخصيات أقل" },
        { en: "One fixed ending", ar: "نهاية واحدة ثابتة" },
      ],
      correct: 0,
      explain: { en: "When choices change the story, players own their version of it.", ar: "حين تغيّر الخيارات القصة، يمتلك اللاعبون نسختهم منها." },
    },
    {
      lv: 7,
      q: { en: "In a game engine, a 'sprite' is…", ar: "في محرك الألعاب، «السبرايت» هو…" },
      choices: [
        { en: "A 2D image that moves in the scene", ar: "صورة ثنائية الأبعاد تتحرك في المشهد" },
        { en: "A sound effect", ar: "مؤثر صوتي" },
        { en: "A bug", ar: "خلل برمجي" },
        { en: "A player's name", ar: "اسم اللاعب" },
      ],
      correct: 0,
      explain: { en: "Characters, coins, clouds — most 2D game objects are sprites.", ar: "الشخصيات والعملات والغيوم — معظم عناصر الألعاب الثنائية سبرايتات." },
    },
    {
      lv: 8,
      q: { en: "In game code, the player's score is stored in a…", ar: "في كود اللعبة، تُخزَّن نقاط اللاعب في…" },
      choices: [{ en: "Variable", ar: "متغيّر" }, { en: "Shadow", ar: "ظل" }, { en: "Pixel", ar: "بكسل" }, { en: "Sound file", ar: "ملف صوتي" }],
      correct: 0,
      explain: { en: "A variable is a named box whose value can change as you play.", ar: "المتغيّر صندوق مسمّى تتغير قيمته أثناء اللعب." },
    },
    {
      lv: 9,
      q: { en: "The main goal of a playtest is to…", ar: "الهدف الأساسي من جلسة الاختبار هو…" },
      choices: [
        { en: "Watch where players struggle", ar: "مراقبة أين يتعثر اللاعبون" },
        { en: "Prove you're right", ar: "إثبات أنك على حق" },
        { en: "Win the game yourself", ar: "أن تفوز أنت باللعبة" },
        { en: "Sell copies", ar: "بيع النسخ" },
      ],
      correct: 0,
      explain: { en: "You learn most from watching real players get stuck — silently.", ar: "تتعلم أكثر من مشاهدة لاعبين حقيقيين يتعثرون — بصمت." },
    },
    {
      lv: 10,
      q: { en: "The most common reason first games never ship is…", ar: "السبب الأكثر شيوعاً لعدم اكتمال الألعاب الأولى هو…" },
      choices: [
        { en: "Too big a scope", ar: "نطاق أكبر من اللازم" },
        { en: "Too small a scope", ar: "نطاق أصغر من اللازم" },
        { en: "Bad computers", ar: "حواسيب سيئة" },
        { en: "No music", ar: "غياب الموسيقى" },
      ],
      correct: 0,
      explain: { en: "Scope small, finish big: a finished tiny game beats an abandoned epic.", ar: "خطّط صغيراً وأنجز كبيراً: لعبة صغيرة مكتملة خير من ملحمة مهجورة." },
    },
  ],
  entrepreneurship: [
    {
      lv: 1,
      q: { en: "Which is a need, not a want?", ar: "أيها حاجة وليس رغبة؟" },
      choices: [
        { en: "Drinking water", ar: "ماء الشرب" },
        { en: "A new video game", ar: "لعبة فيديو جديدة" },
        { en: "Candy", ar: "الحلوى" },
        { en: "A gold watch", ar: "ساعة ذهبية" },
      ],
      correct: 0,
      explain: { en: "Needs keep us alive and safe; wants make life nicer.", ar: "الحاجات تبقينا أحياء وآمنين؛ والرغبات تجعل الحياة أجمل." },
    },
    {
      lv: 2,
      q: { en: "If you save 5 every week, after 4 weeks you have…", ar: "إذا ادخرت ٥ كل أسبوع، فبعد ٤ أسابيع تملك…" },
      choices: [{ en: "20", ar: "20" }, { en: "9", ar: "9" }, { en: "45", ar: "45" }, { en: "25", ar: "25" }],
      correct: 0,
      explain: { en: "Saving is steady: 5 × 4 = 20.", ar: "الادخار انتظام: ٥ × ٤ = ٢٠." },
    },
    {
      lv: 3,
      q: { en: "The best problems to solve are ones that are…", ar: "أفضل المشكلات للحل هي تلك التي تكون…" },
      choices: [
        { en: "Frequent and painful for many people", ar: "متكررة ومؤلمة لكثير من الناس" },
        { en: "Rare and tiny", ar: "نادرة وتافهة" },
        { en: "Already solved well", ar: "محلولة جيداً بالفعل" },
        { en: "Impossible", ar: "مستحيلة" },
      ],
      correct: 0,
      explain: { en: "Frequency × pain × people = the size of the opportunity.", ar: "التكرار × الألم × عدد الناس = حجم الفرصة." },
    },
    {
      lv: 4,
      q: { en: "You sell lemonade for 5 and each cup costs 2 to make. Your profit per cup is…", ar: "تبيع كوب الليمونادة بـ٥ وتكلفة صنعه ٢. ربحك من الكوب هو…" },
      choices: [{ en: "3", ar: "3" }, { en: "7", ar: "7" }, { en: "2", ar: "2" }, { en: "5", ar: "5" }],
      correct: 0,
      explain: { en: "Profit = price − cost = 5 − 2 = 3.", ar: "الربح = السعر − التكلفة = ٥ − ٢ = ٣." },
    },
    {
      lv: 5,
      q: { en: "People don't buy a drill; they buy…", ar: "الناس لا يشترون المثقاب؛ بل يشترون…" },
      choices: [
        { en: "The hole in the wall", ar: "الثقب في الجدار" },
        { en: "The box it comes in", ar: "علبته" },
        { en: "The brand's office", ar: "مكتب الشركة" },
        { en: "The instruction manual", ar: "كتيّب التعليمات" },
      ],
      correct: 0,
      explain: { en: "Customers buy outcomes — the job the product does for them.", ar: "العملاء يشترون النتائج — المهمة التي ينجزها المنتج لهم." },
    },
    {
      lv: 6,
      q: { en: "A subscription business earns money by…", ar: "يكسب نموذج الاشتراك المال عبر…" },
      choices: [
        { en: "Recurring payments for ongoing value", ar: "دفعات متكررة مقابل قيمة مستمرة" },
        { en: "One sale forever", ar: "بيع واحد إلى الأبد" },
        { en: "Only donations", ar: "التبرعات فقط" },
        { en: "Selling the office", ar: "بيع المكتب" },
      ],
      correct: 0,
      explain: { en: "Netflix, Spotify — and wadehAI — trade continuous value for monthly payment.", ar: "نتفليكس وسبوتيفاي — وواضح — تقدم قيمة مستمرة مقابل دفعة شهرية." },
    },
    {
      lv: 7,
      q: { en: "An MVP exists mainly to…", ar: "الهدف الأساسي من المنتج الأوّلي هو…" },
      choices: [
        { en: "Test your riskiest assumption", ar: "اختبار أخطر افتراضاتك" },
        { en: "Impress investors with polish", ar: "إبهار المستثمرين بالإتقان" },
        { en: "Include every feature", ar: "تضمين كل الميزات" },
        { en: "Win design awards", ar: "الفوز بجوائز التصميم" },
      ],
      correct: 0,
      explain: { en: "Build the smallest thing that tells you whether the idea works.", ar: "ابنِ أصغر شيء يخبرك إن كانت الفكرة تنجح." },
    },
    {
      lv: 8,
      q: { en: "A strong pitch opens with…", ar: "العرض القوي يبدأ بـ…" },
      choices: [
        { en: "The problem, told as a story", ar: "المشكلة مروية كقصة" },
        { en: "The team's CVs", ar: "السير الذاتية للفريق" },
        { en: "The font choices", ar: "اختيارات الخطوط" },
        { en: "The office address", ar: "عنوان المكتب" },
      ],
      correct: 0,
      explain: { en: "If the audience feels the problem, they'll lean in for the solution.", ar: "إذا لمس الجمهور المشكلة، انجذبوا لسماع الحل." },
    },
    {
      lv: 9,
      q: { en: "Retention matters more than acquisition because…", ar: "الاحتفاظ بالعملاء أهم من اكتسابهم لأن…" },
      choices: [
        { en: "A leaky bucket never fills", ar: "الدلو المثقوب لا يمتلئ أبداً" },
        { en: "Ads are cheap", ar: "الإعلانات رخيصة" },
        { en: "New users pay more", ar: "المستخدمون الجدد يدفعون أكثر" },
        { en: "It looks good in pitches", ar: "يبدو جيداً في العروض" },
      ],
      correct: 0,
      explain: { en: "If customers keep leaving, no amount of new ones saves the business.", ar: "إذا استمر العملاء بالمغادرة، فلن ينقذ العملَ أيُّ عدد من الجدد." },
    },
    {
      lv: 10,
      q: { en: "Careem's sale to Uber for $3.1B proved that…", ar: "بيع كريم لأوبر بـ٣٫١ مليار دولار أثبت أن…" },
      choices: [
        { en: "Regional startups can reach global scale", ar: "الشركات الناشئة الإقليمية قادرة على بلوغ مستوى عالمي" },
        { en: "Only US startups succeed", ar: "النجاح حكر على الشركات الأمريكية" },
        { en: "Taxis are obsolete", ar: "سيارات الأجرة انتهت" },
        { en: "Apps are easy money", ar: "التطبيقات مال سهل" },
      ],
      correct: 0,
      explain: { en: "Built in Dubai for the region's real needs — then the world paid attention.", ar: "بُنيت في دبي لاحتياجات المنطقة الحقيقية — ثم انتبه لها العالم." },
    },
  ],
  leadership: [
    {
      lv: 1,
      q: { en: "A friend drops their books. A leader-in-training…", ar: "سقطت كتب صديقك. قائد المستقبل…" },
      choices: [
        { en: "Helps pick them up right away", ar: "يساعده في جمعها فوراً" },
        { en: "Laughs", ar: "يضحك" },
        { en: "Walks past", ar: "يمضي في طريقه" },
        { en: "Waits to be asked", ar: "ينتظر أن يُطلب منه" },
      ],
      correct: 0,
      explain: { en: "Leadership starts with helping before being asked.", ar: "تبدأ القيادة بالمساعدة قبل أن تُطلب." },
    },
    {
      lv: 2,
      q: { en: "Whole-body listening means…", ar: "الإصغاء بكامل الجسد يعني…" },
      choices: [
        { en: "Eyes, ears and attention on the speaker", ar: "العينان والأذنان والانتباه نحو المتحدث" },
        { en: "Talking louder", ar: "الكلام بصوت أعلى" },
        { en: "Looking at your phone", ar: "النظر إلى هاتفك" },
        { en: "Planning your reply only", ar: "التفكير في ردك فقط" },
      ],
      correct: 0,
      explain: { en: "People feel heard when your whole attention says 'I'm with you'.", ar: "يشعر الناس بأنهم مسموعون حين يقول انتباهك كله «أنا معك»." },
    },
    {
      lv: 3,
      q: { en: "A good team role for someone who loves details is…", ar: "الدور المناسب في الفريق لمن يحب التفاصيل هو…" },
      choices: [{ en: "Checker / quality lead", ar: "المدقّق / مسؤول الجودة" }, { en: "No role", ar: "بلا دور" }, { en: "Doing everything", ar: "فعل كل شيء" }, { en: "Watching only", ar: "المشاهدة فقط" }],
      correct: 0,
      explain: { en: "Great teams match roles to strengths.", ar: "الفرق العظيمة توائم الأدوار مع نقاط القوة." },
    },
    {
      lv: 4,
      q: { en: "You broke a class rule by mistake. The trust-building move is…", ar: "خرقت قاعدة صفية عن غير قصد. الخطوة التي تبني الثقة هي…" },
      choices: [
        { en: "Owning it before you're caught", ar: "الاعتراف قبل أن يُكشف الأمر" },
        { en: "Hiding it", ar: "إخفاؤه" },
        { en: "Blaming a classmate", ar: "لوم زميل" },
        { en: "Denying everything", ar: "إنكار كل شيء" },
      ],
      correct: 0,
      explain: { en: "Trust is earned in drops and lost in buckets — owning mistakes fills the jar.", ar: "الثقة تُكسب قطرة قطرة وتُفقد دفعة واحدة — والاعتراف بالخطأ يملأ الجرّة." },
    },
    {
      lv: 5,
      q: { en: "Consensus means the group…", ar: "التوافق يعني أن المجموعة…" },
      choices: [
        { en: "Finds a decision everyone can accept", ar: "تصل إلى قرار يقبله الجميع" },
        { en: "Votes and ignores the losers", ar: "تصوّت وتتجاهل الخاسرين" },
        { en: "Lets the loudest decide", ar: "تترك الأعلى صوتاً يقرر" },
        { en: "Never decides", ar: "لا تقرر أبداً" },
      ],
      correct: 0,
      explain: { en: "Slower than voting, but everyone walks out owning the decision.", ar: "أبطأ من التصويت، لكن الجميع يخرجون شركاء في القرار." },
    },
    {
      lv: 6,
      q: { en: "The most motivating praise is…", ar: "أكثر أنواع المديح تحفيزاً هو…" },
      choices: [
        { en: "Specific: naming exactly what was done well", ar: "المحدد: تسمية ما أُتقن بالضبط" },
        { en: "Generic: 'good job' to everyone", ar: "العام: «أحسنت» للجميع" },
        { en: "Comparing people", ar: "المقارنة بين الأشخاص" },
        { en: "Loud and public only", ar: "الصاخب والعلني فقط" },
      ],
      correct: 0,
      explain: { en: "'Your opening slide made the problem vivid' beats 'nice work' every time.", ar: "«شريحتك الافتتاحية جعلت المشكلة حيّة» تتفوق على «عمل جيد» دائماً." },
    },
    {
      lv: 7,
      q: { en: "In a conflict, the first thing to find is…", ar: "في أي خلاف، أول ما ينبغي البحث عنه هو…" },
      choices: [
        { en: "The real issue underneath", ar: "القضية الحقيقية الكامنة" },
        { en: "Who to blame", ar: "من نلوم" },
        { en: "Who is louder", ar: "من صوته أعلى" },
        { en: "A way to avoid everyone", ar: "طريقة لتجنّب الجميع" },
      ],
      correct: 0,
      explain: { en: "Arguments are usually about something deeper than the trigger.", ar: "الخلافات عادة حول شيء أعمق من شرارتها." },
    },
    {
      lv: 8,
      q: { en: "When leading change, start with…", ar: "عند قيادة التغيير، ابدأ بـ…" },
      choices: [
        { en: "A small visible win", ar: "انتصار صغير مرئي" },
        { en: "Changing everything at once", ar: "تغيير كل شيء دفعة واحدة" },
        { en: "A punishment for resisters", ar: "معاقبة المعارضين" },
        { en: "A long speech", ar: "خطاب طويل" },
      ],
      correct: 0,
      explain: { en: "Small wins prove the change works and recruit believers.", ar: "الانتصارات الصغيرة تثبت جدوى التغيير وتكسب المؤمنين به." },
    },
    {
      lv: 9,
      q: { en: "Servant leadership means the leader…", ar: "القيادة الخادمة تعني أن القائد…" },
      choices: [
        { en: "Puts the team's needs first", ar: "يقدّم احتياجات الفريق أولاً" },
        { en: "Gives the most orders", ar: "يُصدر أكثر الأوامر" },
        { en: "Takes the credit", ar: "يستأثر بالفضل" },
        { en: "Avoids decisions", ar: "يتجنب القرارات" },
      ],
      correct: 0,
      explain: { en: "Power is used to serve the people you lead, not yourself.", ar: "تُستخدم السلطة لخدمة من تقودهم، لا لخدمة نفسك." },
    },
    {
      lv: 10,
      q: { en: "Your leadership philosophy should be written…", ar: "ينبغي أن تُكتب فلسفتك القيادية…" },
      choices: [
        { en: "By you, revised as you grow", ar: "بيدك، وتُراجَع كلما نضجت" },
        { en: "Copied from a famous CEO", ar: "منسوخة من مدير شهير" },
        { en: "Once, never to change", ar: "مرة واحدة بلا تغيير" },
        { en: "Only when you get a title", ar: "فقط حين تحصل على منصب" },
      ],
      correct: 0,
      explain: { en: "A philosophy is a living document — titles don't write it, practice does.", ar: "الفلسفة وثيقة حيّة — لا تكتبها المناصب بل الممارسة." },
    },
  ],
  "problem-solving": [
    {
      lv: 1,
      q: { en: "Your tower of blocks falls. The solver's move is…", ar: "انهار برجك من المكعبات. تصرّف الحلّال هو…" },
      choices: [
        { en: "Look at why it fell, then try again", ar: "تأمل سبب السقوط ثم حاول مجدداً" },
        { en: "Cry and quit", ar: "البكاء والانسحاب" },
        { en: "Kick the blocks", ar: "ركل المكعبات" },
        { en: "Blame the blocks", ar: "لوم المكعبات" },
      ],
      correct: 0,
      explain: { en: "Every fall is information: wider base, lower tower, try again.", ar: "كل سقوط معلومة: قاعدة أعرض، برج أخفض، محاولة جديدة." },
    },
    {
      lv: 2,
      q: { en: "The most useful detective question starts with…", ar: "أكثر أسئلة المحقق فائدة يبدأ بـ…" },
      choices: [
        { en: "Why", ar: "لماذا" },
        { en: "Whatever", ar: "مهما يكن" },
        { en: "Never", ar: "أبداً" },
        { en: "Someday", ar: "يوماً ما" },
      ],
      correct: 0,
      explain: { en: "'Why' digs below what happened into what caused it.", ar: "«لماذا» تحفر تحت ما حدث لتصل إلى سببه." },
    },
    {
      lv: 3,
      q: { en: "The best first step with a big, scary problem is to…", ar: "أفضل خطوة أولى مع مشكلة كبيرة مخيفة هي…" },
      choices: [
        { en: "Break it into smaller pieces", ar: "تفكيكها إلى قطع أصغر" },
        { en: "Give up", ar: "الاستسلام" },
        { en: "Solve it all at once", ar: "حلها دفعة واحدة" },
        { en: "Wait for luck", ar: "انتظار الحظ" },
      ],
      correct: 0,
      explain: { en: "Decomposition turns one impossible task into many possible ones.", ar: "التفكيك يحوّل مهمة مستحيلة واحدة إلى مهام ممكنة عديدة." },
    },
    {
      lv: 4,
      q: { en: "In a brainstorm, ideas are judged…", ar: "في العصف الذهني، يُحكم على الأفكار…" },
      choices: [
        { en: "Later — first collect many", ar: "لاحقاً — اجمع الكثير أولاً" },
        { en: "Instantly and harshly", ar: "فوراً وبقسوة" },
        { en: "Never at all", ar: "أبداً" },
        { en: "Only by the teacher", ar: "من المعلم فقط" },
      ],
      correct: 0,
      explain: { en: "Judging too early kills the wild ideas that lead somewhere new.", ar: "الحكم المبكر يقتل الأفكار الجامحة التي تقود إلى الجديد." },
    },
    {
      lv: 5,
      q: { en: "If 'all birds have feathers' and 'a falcon is a bird', then…", ar: "إذا كانت «كل الطيور لها ريش» و«الصقر طائر»، فإن…" },
      choices: [
        { en: "The falcon has feathers", ar: "الصقر له ريش" },
        { en: "The falcon can't fly", ar: "الصقر لا يطير" },
        { en: "All feathers are falcons", ar: "كل ريشة صقر" },
        { en: "Nothing follows", ar: "لا يلزم شيء" },
      ],
      correct: 0,
      explain: { en: "That's deduction: if the premises are true, the conclusion must be.", ar: "هذا هو الاستنباط: إن صدقت المقدمات لزمت النتيجة." },
    },
    {
      lv: 6,
      q: { en: "A feedback loop is when…", ar: "حلقة التغذية الراجعة تحدث حين…" },
      choices: [
        { en: "An effect feeds back into its cause", ar: "تعود النتيجة لتؤثر في سببها" },
        { en: "Two people argue", ar: "يتجادل شخصان" },
        { en: "A plan is written twice", ar: "تُكتب الخطة مرتين" },
        { en: "Music repeats", ar: "تتكرر الموسيقى" },
      ],
      correct: 0,
      explain: { en: "Like a rumour: the more it spreads, the more people spread it.", ar: "كالإشاعة: كلما انتشرت أكثر، زاد من ينشرها." },
    },
    {
      lv: 7,
      q: { en: "Estimate: a school has 40 classes of ~25 students. Total students ≈", ar: "قدّر: مدرسة فيها ٤٠ صفاً بمعدل ~٢٥ طالباً. مجموع الطلاب ≈" },
      choices: [{ en: "1,000", ar: "1,000" }, { en: "100", ar: "100" }, { en: "10,000", ar: "10,000" }, { en: "4,000", ar: "4,000" }],
      correct: 0,
      explain: { en: "40 × 25 = 1,000 — smart estimation beats waiting for perfect data.", ar: "٤٠ × ٢٥ = ١٠٠٠ — التقدير الذكي خير من انتظار البيانات الكاملة." },
    },
    {
      lv: 8,
      q: { en: "Before running an experiment, a good solver writes down…", ar: "قبل إجراء التجربة، يكتب الحلّال الجيد…" },
      choices: [
        { en: "A hypothesis to test", ar: "فرضية للاختبار" },
        { en: "The conclusion", ar: "الاستنتاج النهائي" },
        { en: "Nothing at all", ar: "لا شيء إطلاقاً" },
        { en: "Someone to blame", ar: "اسم من سيلومه" },
      ],
      correct: 0,
      explain: { en: "A written hypothesis keeps the test honest.", ar: "الفرضية المكتوبة تُبقي الاختبار صادقاً." },
    },
    {
      lv: 9,
      q: { en: "Groupthink happens when a team…", ar: "يحدث التفكير القطيعي حين…" },
      choices: [
        { en: "Agrees too fast to avoid conflict", ar: "يتفق الفريق بسرعة مفرطة تجنباً للخلاف" },
        { en: "Argues too much", ar: "يكثر الجدال" },
        { en: "Has too many ideas", ar: "تكثر الأفكار" },
        { en: "Works separately", ar: "يعمل كل فرد وحده" },
      ],
      correct: 0,
      explain: { en: "Harmony feels good but hides risks; invite a devil's advocate.", ar: "الانسجام مريح لكنه يخفي المخاطر؛ ادعُ محامي الشيطان." },
    },
    {
      lv: 10,
      q: { en: "Jordan's water problem is 'a masterclass in constraints' because solvers must…", ar: "مشكلة المياه في الأردن «درس متقدم في القيود» لأن حلّالها يجب أن…" },
      choices: [
        { en: "Balance cost, politics, engineering and nature at once", ar: "يوازن الكلفة والسياسة والهندسة والطبيعة معاً" },
        { en: "Ignore the costs", ar: "يتجاهل التكاليف" },
        { en: "Pick one factor only", ar: "يختار عاملاً واحداً فقط" },
        { en: "Wait for rain", ar: "ينتظر المطر" },
      ],
      correct: 0,
      explain: { en: "Real problems live inside many constraints — that's what the toolkit is for.", ar: "المشكلات الحقيقية تعيش داخل قيود عديدة — ولهذا وُجدت عدّة الحلّال." },
    },
  ],
  "emotional-intelligence": [
    {
      lv: 1,
      q: { en: "Feelings are like visitors because they…", ar: "المشاعر مثل الضيوف لأنها…" },
      choices: [
        { en: "Come and also go", ar: "تأتي وترحل أيضاً" },
        { en: "Never leave", ar: "لا ترحل أبداً" },
        { en: "Are always bad", ar: "سيئة دائماً" },
        { en: "Only visit others", ar: "تزور غيرك فقط" },
      ],
      correct: 0,
      explain: { en: "Even the biggest feeling passes — naming it helps it move along.", ar: "حتى أكبر المشاعر يمرّ — وتسميته تساعده على المرور." },
    },
    {
      lv: 2,
      q: { en: "When anger feels huge, a first good tool is…", ar: "حين يشتد الغضب، أداة أولى جيدة هي…" },
      choices: [
        { en: "Slow belly breathing", ar: "تنفّس البطن البطيء" },
        { en: "Shouting louder", ar: "الصراخ أعلى" },
        { en: "Breaking something", ar: "كسر شيء ما" },
        { en: "Blaming a friend", ar: "لوم صديق" },
      ],
      correct: 0,
      explain: { en: "Slow breathing calms the body so the thinking brain can return.", ar: "التنفس البطيء يهدّئ الجسد ليعود العقل المفكر." },
    },
    {
      lv: 3,
      q: { en: "Empathy is…", ar: "التعاطف هو…" },
      choices: [
        { en: "Feeling with someone", ar: "أن تشعر مع الآخر" },
        { en: "Feeling sorry from far away", ar: "الشفقة من بعيد" },
        { en: "Agreeing with everyone", ar: "موافقة الجميع" },
        { en: "Fixing people", ar: "إصلاح الناس" },
      ],
      correct: 0,
      explain: { en: "Standing in their shoes — not just looking at them.", ar: "أن تقف في مكانهم — لا أن تكتفي بالنظر إليهم." },
    },
    {
      lv: 4,
      q: { en: "A real apology includes…", ar: "الاعتذار الحقيقي يتضمن…" },
      choices: [
        { en: "Naming what you did and repairing it", ar: "تسمية ما فعلت والسعي لإصلاحه" },
        { en: "'Sorry, BUT you…'", ar: "«آسف، لكنك أنت…»" },
        { en: "Saying it fast and running", ar: "قولها سريعاً والهرب" },
        { en: "Waiting until they forget", ar: "انتظار أن ينسوا" },
      ],
      correct: 0,
      explain: { en: "'Sorry but' is not sorry. Name it, own it, repair it.", ar: "«آسف لكن» ليست اعتذاراً. سمِّ الخطأ وتحمّله وأصلحه." },
    },
    {
      lv: 5,
      q: { en: "Reading the room mostly means noticing…", ar: "قراءة الموقف تعني غالباً ملاحظة…" },
      choices: [
        { en: "Tone and body language", ar: "النبرة ولغة الجسد" },
        { en: "The furniture", ar: "الأثاث" },
        { en: "The time", ar: "الوقت" },
        { en: "Your phone", ar: "هاتفك" },
      ],
      correct: 0,
      explain: { en: "Most of what people feel is said without words.", ar: "معظم ما يشعر به الناس يُقال بلا كلمات." },
    },
    {
      lv: 6,
      q: { en: "Resilience means…", ar: "المرونة النفسية تعني…" },
      choices: [
        { en: "Bouncing back after setbacks", ar: "النهوض بعد الكبوات" },
        { en: "Never feeling sad", ar: "ألا تحزن أبداً" },
        { en: "Avoiding all risk", ar: "تجنّب كل مخاطرة" },
        { en: "Hiding feelings", ar: "إخفاء المشاعر" },
      ],
      correct: 0,
      explain: { en: "Everyone falls; resilience is the getting up.", ar: "الكل يقع؛ المرونة هي النهوض." },
    },
    {
      lv: 7,
      q: { en: "A friend pressures you to share your password. The healthy move is…", ar: "يضغط عليك صديق لمشاركة كلمة سرّك. التصرف الصحي هو…" },
      choices: [
        { en: "A kind, firm no", ar: "رفض لطيف وحازم" },
        { en: "Sharing to keep the peace", ar: "المشاركة حفاظاً على الود" },
        { en: "Ending the friendship loudly", ar: "إنهاء الصداقة بضجيج" },
        { en: "Ignoring them forever", ar: "تجاهلهم إلى الأبد" },
      ],
      correct: 0,
      explain: { en: "Boundaries protect both you and the friendship — real friends accept 'no'.", ar: "الحدود تحميك وتحمي الصداقة — والصديق الحقيقي يقبل «لا»." },
    },
    {
      lv: 8,
      q: { en: "A habit sticks best when it is…", ar: "تترسخ العادة أكثر حين تكون…" },
      choices: [
        { en: "Small, daily and tied to a trigger", ar: "صغيرة ويومية ومربوطة بمحفّز" },
        { en: "Huge and occasional", ar: "ضخمة ومتقطعة" },
        { en: "Secret and vague", ar: "سرية وغامضة" },
        { en: "Forced by others", ar: "مفروضة من الآخرين" },
      ],
      correct: 0,
      explain: { en: "After Fajr, five words of vocabulary — small hooks beat big plans.", ar: "بعد الفجر خمس كلمات جديدة — الخطاطيف الصغيرة تغلب الخطط الكبيرة." },
    },
    {
      lv: 9,
      q: { en: "Emotional courage is…", ar: "الشجاعة العاطفية هي…" },
      choices: [
        { en: "Acting right despite the fear", ar: "فعل الصواب رغم الخوف" },
        { en: "Feeling no fear at all", ar: "انعدام الخوف تماماً" },
        { en: "Hiding all weakness", ar: "إخفاء كل ضعف" },
        { en: "Avoiding hard talks", ar: "تجنّب المحادثات الصعبة" },
      ],
      correct: 0,
      explain: { en: "Courage isn't the absence of fear — it's fear, plus the step forward.", ar: "الشجاعة ليست غياب الخوف — بل الخوف مع خطوة إلى الأمام." },
    },
    {
      lv: 10,
      q: { en: "A balanced life charter should weigh ambition against…", ar: "ميثاق الحياة المتوازنة يوازن الطموح مع…" },
      choices: [
        { en: "Rest and relationships", ar: "الراحة والعلاقات" },
        { en: "More ambition", ar: "مزيد من الطموح" },
        { en: "Nothing — ambition is all", ar: "لا شيء — الطموح كل شيء" },
        { en: "Other people's goals", ar: "أهداف الآخرين" },
      ],
      correct: 0,
      explain: { en: "Burnout is ambition without rest; drift is rest without ambition.", ar: "الاحتراق طموح بلا راحة؛ والانجراف راحة بلا طموح." },
    },
  ],
  languages: [
    {
      lv: 1,
      q: { en: "'Merhaba', 'Bonjour' and 'Hello' are all ways to…", ar: "«مرحبا» و«بونجور» و«هيلو» كلها طرق لـ…" },
      choices: [
        { en: "Greet someone", ar: "تحية شخص" },
        { en: "Say goodbye", ar: "الوداع" },
        { en: "Order food", ar: "طلب طعام" },
        { en: "Count to three", ar: "العد إلى ثلاثة" },
      ],
      correct: 0,
      explain: { en: "Every language opens with a greeting — collect them like keys.", ar: "كل لغة تُفتح بتحية — اجمعها كما تجمع المفاتيح." },
    },
    {
      lv: 2,
      q: { en: "The fastest way to remember a new phrase is to…", ar: "أسرع طريقة لتذكّر عبارة جديدة هي…" },
      choices: [
        { en: "Use it today in real life", ar: "استخدامها اليوم في الحياة الفعلية" },
        { en: "Read it once silently", ar: "قراءتها مرة بصمت" },
        { en: "Save it for the exam", ar: "تركها للامتحان" },
        { en: "Write it 100 times", ar: "كتابتها ١٠٠ مرة" },
      ],
      correct: 0,
      explain: { en: "Language lives in use: order the juice, greet the neighbour.", ar: "اللغة تحيا بالاستعمال: اطلب العصير وحيِّ الجار." },
    },
    {
      lv: 3,
      q: { en: "Spaced repetition means reviewing words…", ar: "المراجعة المتباعدة تعني مراجعة الكلمات…" },
      choices: [
        { en: "At growing intervals over days", ar: "على فترات متزايدة عبر الأيام" },
        { en: "Once and never again", ar: "مرة واحدة فقط" },
        { en: "All in one night", ar: "كلها في ليلة واحدة" },
        { en: "Only before exams", ar: "قبل الامتحانات فقط" },
      ],
      correct: 0,
      explain: { en: "Memory strengthens most when you recall just before forgetting.", ar: "تقوى الذاكرة أكثر حين تتذكر قُبيل النسيان." },
    },
    {
      lv: 4,
      q: { en: "The healthiest attitude to grammar mistakes is…", ar: "الموقف الأصح من أخطاء القواعد هو…" },
      choices: [
        { en: "They're data — make them, learn, move on", ar: "إنها بيانات — أخطئ وتعلّم وواصل" },
        { en: "Silence until perfect", ar: "الصمت حتى الإتقان" },
        { en: "Shame and avoidance", ar: "الخجل والتجنب" },
        { en: "Ignoring grammar forever", ar: "تجاهل القواعد للأبد" },
      ],
      correct: 0,
      explain: { en: "Speakers who make brave mistakes learn faster than silent perfectionists.", ar: "من يخطئ بشجاعة يتعلم أسرع ممن يصمت طلباً للكمال." },
    },
    {
      lv: 5,
      q: { en: "'Shadowing' a speaker means…", ar: "«محاكاة» المتحدث تعني…" },
      choices: [
        { en: "Repeating right behind their voice", ar: "الترديد خلف صوته مباشرة" },
        { en: "Following them home", ar: "اتباعه إلى بيته" },
        { en: "Writing their biography", ar: "كتابة سيرته" },
        { en: "Staying silent", ar: "التزام الصمت" },
      ],
      correct: 0,
      explain: { en: "You mimic rhythm and sounds in real time — the fastest route to accent and flow.", ar: "تحاكي الإيقاع والأصوات لحظياً — أسرع طريق للنطق والانسياب." },
    },
    {
      lv: 6,
      q: { en: "When you meet an unknown word while reading, first…", ar: "حين تقابل كلمة مجهولة أثناء القراءة، أولاً…" },
      choices: [
        { en: "Guess it from context", ar: "خمّنها من السياق" },
        { en: "Stop reading", ar: "توقف عن القراءة" },
        { en: "Skip the book", ar: "اترك الكتاب" },
        { en: "Memorise the page", ar: "احفظ الصفحة" },
      ],
      correct: 0,
      explain: { en: "Context carries most meanings; the dictionary comes second.", ar: "السياق يحمل معظم المعاني؛ والقاموس يأتي ثانياً." },
    },
    {
      lv: 7,
      q: { en: "The discipline of good writing is…", ar: "انضباط الكتابة الجيدة هو…" },
      choices: [
        { en: "Saying more with fewer words", ar: "قول الكثير بكلمات أقل" },
        { en: "Using the longest words", ar: "استخدام أطول الكلمات" },
        { en: "Never editing", ar: "عدم التحرير أبداً" },
        { en: "Writing only once", ar: "الكتابة مرة واحدة فقط" },
      ],
      correct: 0,
      explain: { en: "First drafts talk; edited drafts speak.", ar: "المسودة الأولى تثرثر؛ والمسودة المحررة تتكلم." },
    },
    {
      lv: 9,
      q: { en: "Code-switching is…", ar: "التنقل اللغوي هو…" },
      choices: [
        { en: "Moving between languages mid-conversation", ar: "الانتقال بين اللغات في الحديث الواحد" },
        { en: "Writing computer code", ar: "كتابة كود برمجي" },
        { en: "Forgetting your first language", ar: "نسيان لغتك الأولى" },
        { en: "Speaking in secret codes", ar: "التحدث برموز سرية" },
      ],
      correct: 0,
      explain: { en: "'Yalla let's go, on y va!' — multilinguals switch by audience and mood.", ar: "«يلا let's go!» — متعددو اللغات ينتقلون بحسب الجمهور والمزاج." },
    },
    {
      lv: 10,
      q: { en: "Having learned language two with a method, language three is…", ar: "بعد تعلّم اللغة الثانية بمنهجية، تصبح اللغة الثالثة…" },
      choices: [
        { en: "Faster — you know how you learn", ar: "أسرع — لأنك عرفت كيف تتعلم" },
        { en: "Impossible", ar: "مستحيلة" },
        { en: "Exactly as slow", ar: "بالبطء نفسه تماماً" },
        { en: "Pointless", ar: "بلا فائدة" },
      ],
      correct: 0,
      explain: { en: "The real prize of language two is the method — it compounds.", ar: "الجائزة الحقيقية للغة الثانية هي المنهجية — وهي تتراكم." },
    },
  ],
};
